ls:
  .config.json: camelCase | PascalCase | kebab-case
  .project.json: camelCase | PascalCase | kebab-case
  .js: camelCase | PascalCase | kebab-case
  .jsx: camelCase | PascalCase | kebab-case
  .d.ts: camelCase | PascalCase | kebab-case
  .ts: camelCase | PascalCase | kebab-case
  .tsx: camelCase | PascalCase | kebab-case
  .vue: camelCase | PascalCase | kebab-case
  .config.js: camelCase | PascalCase | kebab-case
  .config.dev.js: camelCase | PascalCase | kebab-case
  .config.development.js: camelCase | PascalCase | kebab-case
  .config.staging.js: camelCase | PascalCase | kebab-case
  .config.prod.js: camelCase | PascalCase | kebab-case
  .config.production.js: camelCase | PascalCase | kebab-case
  .config.ts: camelCase | PascalCase | kebab-case
  .config.dev.ts: camelCase | PascalCase | kebab-case
  .config.development.ts: camelCase | PascalCase | kebab-case
  .config.staging.ts: camelCase | PascalCase | kebab-case
  .config.prod.ts: camelCase | PascalCase | kebab-case
  .config.production.ts: camelCase | PascalCase | kebab-case
  .test.js: camelCase | PascalCase | kebab-case
  .test.ts: camelCase | PascalCase | kebab-case
  .spec.js: camelCase | PascalCase | kebab-case
  .spec.ts: camelCase | PascalCase | kebab-case
  .css: camelCase | PascalCase | kebab-case
  .less: camelCase | PascalCase | kebab-case
  .sass: camelCase | PascalCase | kebab-case
  .scss: camelCase | PascalCase | kebab-case
  .module.css: camelCase | PascalCase | kebab-case
  .module.less: camelCase | PascalCase | kebab-case
  .module.sass: camelCase | PascalCase | kebab-case
  .module.scss: camelCase | PascalCase | kebab-case

ignore:
  - logs
  - report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json
  - pids
  - lib-cov
  - coverage
  - .nyc_output
  - .grunt
  - bower_components
  - .lock-wscript
  - buildRelease
  - node_modules
  - jspm_packages
  - web_modules
  - .npm
  - .eslintcache
  - .rpt2_cache
  - .rts2_cache_cjs
  - .rts2_cache_es
  - .rts2_cache_umd
  - .node_repl_history
  - .yarn-integrity
  - .env
  - .env.test
  - .env.*.test
  - .env.local
  - .env.*.local
  - .cache
  - .parcel-cache
  - dist_electron
  - .next
  - out
  - .umi
  - .umi-production
  - .umi-test
  - .nuxt
  - dist
  - .rax
  - .cache
  - .vuepressdist
  - .serverless
  - .fusebox
  - .dynamodb
  - .tern-port
  - .vscode-test
  - .vscode
  - .idea
  - .hbuilder
  - .hbuilderx
  - .yarncache
  - .yarnunplugged
  - .yarnbuild-state.yml
  - .yarninstall-state.gz
  - .pnp.*
  - .DS_Store
  - .commitlintrc.js
  - .commitlintrc.json
  - .eslintrc.js
  - .eslintrc.json
  - .lintstagedrc.js
  - .lintstagedrc.json
  - .markdownlintrc.js
  - .markdownlint.json
  - .prettierrc.js
  - .prettierrc.json
  - .stylelintrc.js
  - .stylelintrc.json
