name: sync

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: git@github.com:MillCloud/boilerplate-uni-app-vue2.git
          destination-repo: git@gitee.com:MillCloud/boilerplate-uni-app-vue2.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
